### ISSUE TITLE
system.properties giving a wrong ss58Format of 42

### ISSUE THREAD

**Issue by Tbaut** [GMorDIE/gm_chain#16]
Hi there, the `system.properties` doesn't give the correct value for `ss58Format`, there's a mismatch between this and the metadata (7013) which has the side effect of throwing errors for tools such as `generate_metadata` from Parity Signer
```
system.properties: ChainProperties

{
  ss58Format: 42
  tokenDecimals: [
    12
  ]
  tokenSymbol: [
    FREN
  ]
}
```

**Comment by arrudagates** [comment]
That's an issue with whatever node you're connected to, they're using an outdated spec.

**Comment by Tbaut** [comment]
I see, there's not a single node with the right spec available from polkadot.js/apps:
- `wss://kusama.gmordie.com` ~is down~ - edit: looks like it's back up, this one is fine indeed
- `wss://ws.gm.bldnodes.org` and `wss://ws-node-gm.terrabiodao.org`
- the light client doesn't work for me either

**Comment by arrudagates** [comment]
Oh, I see, I'll forward the instructions on updating the spec to them,
thanks for forwarding the information!

**Comment by arrudagates** [comment]
I'll keep this open while we finish updating the nodes actually

**Comment by arrudagates** [comment]
Alright, should be all good now, all 3 rpc endpoints have updated the properties!

**Comment by Tbaut** [comment]
Looks good muito obrigado :)
